### ISSUE TITLE
many 'Transaction failed with HTTP401' logs (and not working federation)

### ISSUE THREAD

**Issue by fedekunz** [secret-telegram/chat#20]
### Background information

- Dendrite version or git SHA: 0.11.1
- Monolith or Polylith?: monolith
- SQLite3 or Postgres?: database
- Running in Docker?: no
- go version: go version go1.20 linux/amd64
- Client used (if applicable): Element

### Description
- What is the problem: Do not send or receive any messages
- Who is affected: anyone in contact with my dendrite server
- How is this bug manifesting: many Transaction failed with HTTP401 in logfile
- When did this first appear: after proxy before dendrite was offline for a few days

**Comment by jolunna** [comment]
Recorded
